name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'patrykandpatrick/vico'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          path: vico
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v6
      - run: |
          cd ${{ github.workspace }}/vico
          VERSION_NAME=$(grep -oP "(?<=const val VICO = \")[^\"]*" buildSrc/src/main/kotlin/Versions.kt)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=v$VERSION_NAME" >> $GITHUB_ENV
          IS_PRERELEASE=false
          echo $VERSION_NAME | grep -q "alpha\|beta\|next" && IS_PRERELEASE=true
          echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV
          ./gradlew assembleDebug
          cd sample/android/build/outputs/apk/debug
          mv android-debug.apk android-sample-debug.apk
      - uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: ${{ github.workspace }}/vico/sample/android/build/outputs/apk/debug/android-sample-debug.apk
          prerelease: ${{ env.IS_PRERELEASE }}
          tag_name: ${{ env.TAG_NAME }}
      - run: |
          cd ${{ github.workspace }}/vico
          ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
