name: Run detekt & checks
on:
  workflow_dispatch:
  push:
jobs:
  run_detekt:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
      - name: Restore Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Run detekt
        id: run_detekt
        run: ./gradlew detekt
        continue-on-error: true
      - name: Upload detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt report
          path: build/reports/detekt/**.html
      - name: Force failure if needed
        if: steps.run_detekt.outcome != 'success'
        run: exit 1
  run_checks:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
      - name: Restore Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Run checks
        run: ./gradlew check
      - name: Upload lint report
        uses: actions/upload-artifact@v2
        with:
          name: Lint report
          path: app/build/reports/**.html
